modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "advancementinfo"
version = "${version}"
displayName = "${name}"
authors = "cassiancc"
description = '''
Show more information about advancement requirements, a port of AdvancementInfo to Architectury.
'''
logoFile = "icon.png"
issueTrackerURL = "https://github.com/cassiancc/Advancement-Info-Plus/issues"
displayURL="https://modrinth.com/mod/advancementinfo+"
modURL="https://modrinth.com/mod/advancementinfo+"

